config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "static#home"

  get '/auth/facebook/callback' => 'sessions#create' # params to user model 

  resources :users, only: [:create, :show, :destroy, :edit, :update] do
    resources :courses, only: [:index]
  end

  get '/login' => 'users#login'
  post '/signin' => 'users#sign_in'
  get '/signup' => 'users#new'

  resources :courses, only: [:index, :new, :create] do
    resources :lessons, only: [:new, :create]
  end
  get '/courses/:slug' => 'courses#show', as: 'course'
  post '/courses/:id/enroll' => 'courses#enroll'

  resources :lessons do 
    resources :contents, only: [:new, :create, :update]
  end
  post '/lessons/:id/publish' => 'lessons#publish'
  delete '/lessons/:id/delete' => 'lessons#destroy', as: 'delete_lesson'

  resources :categories, only: [:index, :show]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :lessons
    has_many :course_categories
    has_many :courses, through: :course_categories

end

app/models/content.rb
class Content < ApplicationRecord

    belongs_to :lesson

    validates :data, presence: true

    enum data_type: [:heading, :paragraph, :image]

    def self.data_types
        ["heading", "paragraph", "image"]
    end

end

app/models/course.rb
class Course < ApplicationRecord

    has_many :user_courses
    has_many :users, through: :user_courses
    has_many :units
    has_many :course_lessons
    has_many :lessons, through: :course_lessons
    has_many :course_categories
    has_many :categories, through: :course_categories

    before_validation :downcase_title
    validate :valid_title
    validates :title, uniqueness: true

    def slug
        self.title.gsub(" ", "-").downcase
    end

    def self.find_by_slug(slug)
        title = slug.gsub("-", " ").downcase
        self.find_by(title: title)
    end

    def instructors
        self.users.select do |user|
            user.authorization == "instructor" || user.authorization == "admin"
        end
    end

    def students
        self.users.select do |user|
            user.authorization == "student"
        end
    end

    def self.user_courses(user)
        Course.all.select do |course|
            course.users.include?(user)
        end
    end

    private

    def downcase_title
        self.title = self.title.downcase
    end

    def valid_title
        if !self.title.scan(/[\-\,\!\*\@\#\$\%\^\&\(\)]/).empty?
            self.errors.add(:title, "You many only have letters and numbers in your title")
        end
    end

end

app/models/course_category.rb
class CourseCategory < ApplicationRecord

    belongs_to :course
    belongs_to :category

end

app/models/course_lesson.rb
class CourseLesson < ApplicationRecord

    belongs_to :course
    belongs_to :lesson

end

app/models/lesson.rb
class Lesson < ApplicationRecord

    belongs_to :category
    has_many :lesson_units
    has_many :units, through: :lesson_units
    has_many :course_lessons
    has_many :courses, through: :course_lessons
    has_many :contents
    has_many :user_lessons
    has_many :users, through: :user_lessons

    # accepts_nested_attributes_for :category


    validates :title, presence: true

    def category_attributes=(category_attributes)
        self.category = Category.find_or_create_by(category_attributes)
    end

end

app/models/lesson_unit.rb
class LessonUnit < ApplicationRecord

    belongs_to :lesson
    belongs_to :unit

end

app/models/unit.rb
class Unit < ApplicationRecord

    belongs_to :course
    has_many :lesson_units
    has_many :lessons, through: :lesson_units

end

app/models/user.rb
class User < ApplicationRecord

    has_many :user_courses
    has_many :courses, through: :user_courses
    has_many :user_lessons
    has_many :lessons, through: :user_lessons    

    has_secure_password

    validates :name, :email, presence: true
    # validates :password, length: {minimum: 1}, if: -> {password.present?}

    enum authorization: [:admin, :instructor, :student]

    private

    # def credentials
    #     if !self.uid
    # end
end

app/models/user_course.rb
class UserCourse < ApplicationRecord

    belongs_to :user
    belongs_to :course

end

app/models/user_lesson.rb
class UserLesson < ApplicationRecord

    belongs_to :user
    belongs_to :lesson

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

    def index
        if params[:user_id]
            if params[:user_id].to_i == current_user.id
                @user = current_user
                @courses = Course.user_courses(@user)
            else
                redirect_to :root
            end
        else
            @courses = Course.all
        end
    end

    def show
        @course = Course.find_by_slug(params[:slug])
        @instructors = @course.instructors
        @students = @course.students
        @lessons = @course.lessons
    end

    def enroll
        @course = Course.find(params[:id])
        current_user.courses << @course
        redirect_to "/courses/#{@course.slug}"
    end

    def new 
        @course = Course.new
    end

    def create
        @course = Course.new(course_params)
        @course.users << current_user
        if @course.save
            redirect_to course_path(@course.slug)
        else
            render :new
        end
    end

    private

    def course_params
        params.require(:course).permit(:title) 
    end



end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    if user_signed_in?
      redirect_to user_path(current_user)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login 
    if user_signed_in?
      redirect_to current_user
    end
    @user = User.new
    @path = "login"
  end

  def sign_in
    user = User.find_by(email: params[:user][:email])
    if !!user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to current_user
    else
      @user = user
      @path = 'login'
      redirect_to login_path, alert: "Unable to find user. Please check your credentials"
    end
  end

  def new
    if user_signed_in?
      redirect_to current_user
    end
    @user = User.new
    @path = "new"
  end

  def create
    user = User.new(user_params)
    if params[:instructor_token] == "secret"
      user.instructor!
    else
      user.student!
    end

    if user.save
      session[:user_id] = user.id
      redirect_to current_user
    else
      @user = user
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @lessons = @user.lessons
    @edit_privileges = @user == current_user 
  end

  def destroy
    session.clear
    redirect_to '/'
  end

  def edit
    if current_user.id != params[:id].to_i
      redirect_to :root
    end
  end

  def update
    current_user.update(user_params)
    redirect_to current_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bio.html.erb
<div class="bio">
<% #binding.pry %>
    <% if bio %>
        <p><%= bio %></p>
    <% elsif user && bio == nil %>
        <%= form_for user do |f| %>
            <%= f.label :bio, "Add a Biography" %><br>
            <%= f.text_area :bio %><br>

            <%= f.submit "update biography" %>
        <% end %>
    <% end %>
</div>

app/views/users/_edit_form.html.erb
<h3>Edit Your Profile Content</h3>

<%= form_for user do |f| %>

    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    
    <%= f.label :email %><br>
    <%= f.email_field :email %><br>
    
    <%= f.label :bio, "Biography" %><br>
    <%= f.text_area :bio %><br>
    
    <%= f.submit %>
<% end %>

app/views/users/_new_user_form.html.erb
<h3>New User</h3>

<% if !user.errors.messages.empty? %>
    <h5 style="color: red;">Please review your submission</h5>
    <ul>
    <% user.errors.messages.each do |parameter, message| %>
        <li><%= parameter %>: <%= message[0] %></li>
    <% end %>
    </ul>

<% end %>

<%= form_for user do |f| %>

    <%= f.label :name %><br>
    <%= f.text_field :name %><br>

    <%= f.label :email %><br>
    <%= f.email_field :email %><br>

    <%= f.label :password %><br>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirm, "Confirm Password" %><br>
    <%= f.password_field :password_confirm %><br>

    <%= f.submit %>


<% end %>

app/views/users/_user_form.html.erb
<h3><%= path == "new" ? "Sign Up" : "Login"  %></h3>

<% if !user.errors.messages.empty? %>
    <h5 style="color: red;">Please review your submission</h5>
    <ul>
    <% user.errors.messages.each do |parameter, message| %>
        <li><%= parameter %>: <%= message[0] %></li>
    <% end %>
    </ul>

<% end %>

<%= form_for user, url: path == "new" ? users_path : signin_path do |f| %>

    <% if path == "new" %>
        <%= f.label :name %><br>
        <%= f.text_field :name %><br>
    <% end %>

    <%= f.label :email %><br>
    <%= f.email_field :email %><br>

    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
    
    <% if path == "new" %>
        <%= f.label :password_confirm, "Confirm Password" %><br>
        <%= f.password_field :password_confirm %><br>
    <% end %>

    <% if path == "new" %>
        <h5>If you would like to sign up as an instructor, provide your special token below: </h5>
        <%= label_tag :instructor_token %><br>
        <%= text_field_tag :instructor_token %><br>
        <%= f.submit "Sign Up" %>
    <% else %>
        <%= f.submit "Login" %>
    <% end %>


<% end %>

app/views/users/edit.html.erb

<%= render partial: "edit_form", locals: {user: current_user} %>

app/views/users/login.html.erb
<div class='user-form'>
    <% if alert %>
    <h5><%= alert %></h5>
    <% end %>

    <%= render partial: 'users/user_form', locals: {user: @user, path: @path} %>
</div>

app/views/users/new.html.erb
<div class="user-form">
    <%= render partial: 'users/user_form', locals: {user: @user, path: @path} %>
</div>

app/views/users/show.html.erb
<h3><%= @user.name %></h3>


<% if @edit_privileges %>
    <%= render partial: "bio", locals: {bio: @user.bio, user: @user} %>
<% else %>
    <%= render partial: "bio", locals: {bio: @user.bio, user: nil} %>
<% end %>

<% if @user == current_user %>
    <%= link_to "edit", edit_user_path(current_user) %>
<% end %>