config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "static#home"

  get '/auth/facebook/callback' => 'sessions#create' # params to user model 

  resources :users, only: [:create, :show, :destroy, :edit, :update] do
    resources :courses, only: [:index]
  end

  get '/login' => 'users#login'
  post '/signin' => 'users#sign_in'
  get '/signup' => 'users#new'

  resources :courses, only: [:index, :new, :create] do
    resources :lessons, only: [:new, :create]
  end
  get '/courses/:slug' => 'courses#show', as: 'course'
  post '/courses/:id/enroll' => 'courses#enroll'

  resources :lessons do 
    resources :contents, only: [:new, :create, :update]
  end
  post '/lessons/:id/publish' => 'lessons#publish'
  delete '/lessons/:id/delete' => 'lessons#destroy', as: 'delete_lesson'

  resources :categories, only: [:index, :show]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :lessons
    has_many :course_categories
    has_many :courses, through: :course_categories

end

app/models/content.rb
class Content < ApplicationRecord

    belongs_to :lesson

    validates :data, presence: true

    enum data_type: [:heading, :paragraph, :image]

    def self.data_types
        ["heading", "paragraph", "image"]
    end

end

app/models/course.rb
class Course < ApplicationRecord

    has_many :user_courses
    has_many :users, through: :user_courses
    has_many :units
    has_many :course_lessons
    has_many :lessons, through: :course_lessons
    has_many :course_categories
    has_many :categories, through: :course_categories

    before_validation :downcase_title
    validate :valid_title
    validates :title, uniqueness: true

    def slug
        self.title.gsub(" ", "-").downcase
    end

    def self.find_by_slug(slug)
        title = slug.gsub("-", " ").downcase
        self.find_by(title: title)
    end

    def instructors
        self.users.select do |user|
            user.authorization == "instructor" || user.authorization == "admin"
        end
    end

    def students
        self.users.select do |user|
            user.authorization == "student"
        end
    end

    def self.user_courses(user)
        Course.all.select do |course|
            course.users.include?(user)
        end
    end

    private

    def downcase_title
        self.title = self.title.downcase
    end

    def valid_title
        if !self.title.scan(/[\-\,\!\*\@\#\$\%\^\&\(\)]/).empty?
            self.errors.add(:title, "You many only have letters and numbers in your title")
        end
    end

end

app/models/course_category.rb
class CourseCategory < ApplicationRecord

    belongs_to :course
    belongs_to :category

end

app/models/course_lesson.rb
class CourseLesson < ApplicationRecord

    belongs_to :course
    belongs_to :lesson

end

app/models/lesson.rb
class Lesson < ApplicationRecord

    belongs_to :category
    has_many :lesson_units
    has_many :units, through: :lesson_units
    has_many :course_lessons
    has_many :courses, through: :course_lessons
    has_many :contents
    has_many :user_lessons
    has_many :users, through: :user_lessons

    # accepts_nested_attributes_for :category


    validates :title, presence: true

    def category_attributes=(category_attributes)
        self.category = Category.find_or_create_by(category_attributes)
    end

end

app/models/lesson_unit.rb
class LessonUnit < ApplicationRecord

    belongs_to :lesson
    belongs_to :unit

end

app/models/unit.rb
class Unit < ApplicationRecord

    belongs_to :course
    has_many :lesson_units
    has_many :lessons, through: :lesson_units

end

app/models/user.rb
class User < ApplicationRecord

    has_many :user_courses
    has_many :courses, through: :user_courses
    has_many :user_lessons
    has_many :lessons, through: :user_lessons    

    has_secure_password

    validates :name, :email, presence: true
    # validates :password, length: {minimum: 1}, if: -> {password.present?}

    enum authorization: [:admin, :instructor, :student]

    private

    # def credentials
    #     if !self.uid
    # end
end

app/models/user_course.rb
class UserCourse < ApplicationRecord

    belongs_to :user
    belongs_to :course

end

app/models/user_lesson.rb
class UserLesson < ApplicationRecord

    belongs_to :user
    belongs_to :lesson

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

    def index
        
    end

    def show
        @lesson = Lesson.find(params[:id])
        @contents = @lesson.contents
        if !@lesson.published
            redirect_to user_courses_path(current_user) unless privileged 
        else
            @contents = @lesson.contents
        end
    end

    def publish
        @lesson = Lesson.find(params[:id])
        if params[:publish] == "true"
            @lesson.published = true
        else
            @lesson.published = false
        end
        @lesson.save
        redirect_to @lesson
    end

    def new 
        @course = Course.find(params[:course_id])
        @lesson = Lesson.new
        @lesson.category = Category.new
        
    end

    def create 
        @course = Course.find(params[:course_id])
        @lesson = Lesson.create(lesson_params)
        @lesson.courses << @course
        @lesson.users << current_user
        @lesson.published = false
        if @lesson.save
            redirect_to new_lesson_content_path(@lesson)
        else
            @lesson.category = Category.new
            render :new
        end
    end

    def destroy
        @lesson = Lesson.find(params[:id])
        @lesson.delete
        redirect_to user_courses_path(current_user)
    end

    def edit
        @lesson = Lesson.find(params[:id])
        @contents = @lesson.contents
    end

    private

    def lesson_params
        params.require(:lesson).permit(:title, category_attributes: [:title])
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    if user_signed_in?
      redirect_to user_path(current_user)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login 
    if user_signed_in?
      redirect_to current_user
    end
    @user = User.new
    @path = "login"
  end

  def sign_in
    user = User.find_by(email: params[:user][:email])
    if !!user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to current_user
    else
      @user = user
      @path = 'login'
      redirect_to login_path, alert: "Unable to find user. Please check your credentials"
    end
  end

  def new
    if user_signed_in?
      redirect_to current_user
    end
    @user = User.new
    @path = "new"
  end

  def create
    user = User.new(user_params)
    if params[:instructor_token] == "secret"
      user.instructor!
    else
      user.student!
    end

    if user.save
      session[:user_id] = user.id
      redirect_to current_user
    else
      @user = user
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @lessons = @user.lessons
    @edit_privileges = @user == current_user 
  end

  def destroy
    session.clear
    redirect_to '/'
  end

  def edit
    if current_user.id != params[:id].to_i
      redirect_to :root
    end
  end

  def update
    current_user.update(user_params)
    redirect_to current_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lessons/_categories_form.html.erb


<%= f.fields_for :category, lesson.category do |category| %>
    <%= category.label :title, "Category" %><br>
    <%= category.text_field :title, list: "categories_autocomplete" %><br>
    <datalist id="categories_autocomplete">
        <% Category.all.each do |category| %>
            <option value="<%= category.title %>">
        <% end %>
    </datalist>
<% end %>

app/views/lessons/_lesson.html.erb
<li><%= link_to lesson.title, lesson_path(lesson) %></li>

app/views/lessons/_lesson_form.html.erb

<%= form_for lesson, url: course_lessons_path(course) do |f| %>

    <%= f.label :title %><br>
    <%= f.text_field :title %><br>

    <%= render partial: "lessons/categories_form", locals: {f: f, lesson: lesson} %>

    <%= f.submit %>

<% end %>

app/views/lessons/_publish_buttons.html.erb

<div class="lesson-buttons">

    <% if !lesson.published %>
        <%= button_to "Publish", "/lessons/#{lesson.id}/publish", params: {publish: true} %>
    <% else %>
        <%= button_to "Unpublish", "/lessons/#{lesson.id}/publish", params: {publish: false} %>
    <% end %>

        <%= button_to "Edit Lesson", edit_lesson_path(lesson), method: :get %>
        <%= button_to "Delete Lesson",delete_lesson_path(lesson), method: :delete %>
</div>

app/views/lessons/edit.html.erb
<h3>Lesson Editor</h3>

<% @contents.each do |content| %>
    <% # posts each content block to content#update %>
    <%= render partial: "contents/content_form", locals: {content: content, path: lesson_content_path(@lesson, content)}%>
<% end %>

<%= render partial: "contents/content_form", locals: {content: Content.new, path: lesson_contents_path(@lesson)}%>

<%= button_to "Preview", lesson_path(@lesson), method: :get %>

app/views/lessons/new.html.erb
<h1><%= @course.title.titlecase %></h1>

<h3>New Lesson</h3>

<%= render partial: "lessons/lesson_form", locals: {lesson: @lesson, course: @course} %>


app/views/lessons/show.html.erb
<h1><%= @lesson.title %></h1>
<h3>Category: <%= @lesson.category.title %></h3>

<%= render partial: "contents/content", locals: {contents: @contents} %>

<% if (@lesson.users.include?(current_user) && privileged) %>
    <%= render partial: "publish_buttons", locals: {lesson: @lesson} %>
<% end %>