config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "static#home"

  get '/auth/facebook/callback' => 'sessions#create' # params to user model 

  resources :users, only: [:create, :show, :destroy, :edit, :update] do
    resources :courses, only: [:index]
  end

  get '/login' => 'users#login'
  post '/signin' => 'users#sign_in'
  get '/signup' => 'users#new'

  resources :courses, only: [:index, :new, :create] do
    resources :lessons, only: [:new, :create]
  end
  get '/courses/:slug' => 'courses#show', as: 'course'
  post '/courses/:id/enroll' => 'courses#enroll'

  resources :lessons do 
    resources :contents, only: [:new, :create, :update]
  end
  post '/lessons/:id/publish' => 'lessons#publish'
  delete '/lessons/:id/delete' => 'lessons#destroy', as: 'delete_lesson'

  resources :categories, only: [:index, :show]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :lessons
    has_many :course_categories
    has_many :courses, through: :course_categories

end

app/models/content.rb
class Content < ApplicationRecord

    belongs_to :lesson

    validates :data, presence: true

    enum data_type: [:heading, :paragraph, :image]

    def self.data_types
        ["heading", "paragraph", "image"]
    end

end

app/models/course.rb
class Course < ApplicationRecord

    has_many :user_courses
    has_many :users, through: :user_courses
    has_many :units
    has_many :course_lessons
    has_many :lessons, through: :course_lessons
    has_many :course_categories
    has_many :categories, through: :course_categories

    before_validation :downcase_title
    validate :valid_title
    validates :title, uniqueness: true

    def slug
        self.title.gsub(" ", "-").downcase
    end

    def self.find_by_slug(slug)
        title = slug.gsub("-", " ").downcase
        self.find_by(title: title)
    end

    def instructors
        self.users.select do |user|
            user.authorization == "instructor" || user.authorization == "admin"
        end
    end

    def students
        self.users.select do |user|
            user.authorization == "student"
        end
    end

    def self.user_courses(user)
        Course.all.select do |course|
            course.users.include?(user)
        end
    end

    private

    def downcase_title
        self.title = self.title.downcase
    end

    def valid_title
        if !self.title.scan(/[\-\,\!\*\@\#\$\%\^\&\(\)]/).empty?
            self.errors.add(:title, "You many only have letters and numbers in your title")
        end
    end

end

app/models/course_category.rb
class CourseCategory < ApplicationRecord

    belongs_to :course
    belongs_to :category

end

app/models/course_lesson.rb
class CourseLesson < ApplicationRecord

    belongs_to :course
    belongs_to :lesson

end

app/models/lesson.rb
class Lesson < ApplicationRecord

    belongs_to :category
    has_many :lesson_units
    has_many :units, through: :lesson_units
    has_many :course_lessons
    has_many :courses, through: :course_lessons
    has_many :contents
    has_many :user_lessons
    has_many :users, through: :user_lessons

    # accepts_nested_attributes_for :category


    validates :title, presence: true

    def category_attributes=(category_attributes)
        self.category = Category.find_or_create_by(category_attributes)
    end

end

app/models/lesson_unit.rb
class LessonUnit < ApplicationRecord

    belongs_to :lesson
    belongs_to :unit

end

app/models/unit.rb
class Unit < ApplicationRecord

    belongs_to :course
    has_many :lesson_units
    has_many :lessons, through: :lesson_units

end

app/models/user.rb
class User < ApplicationRecord

    has_many :user_courses
    has_many :courses, through: :user_courses
    has_many :user_lessons
    has_many :lessons, through: :user_lessons    

    has_secure_password

    validates :name, :email, presence: true
    # validates :password, length: {minimum: 1}, if: -> {password.present?}

    enum authorization: [:admin, :instructor, :student]

    private

    # def credentials
    #     if !self.uid
    # end
end

app/models/user_course.rb
class UserCourse < ApplicationRecord

    belongs_to :user
    belongs_to :course

end

app/models/user_lesson.rb
class UserLesson < ApplicationRecord

    belongs_to :user
    belongs_to :lesson

end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_banner.html.erb
<div class="banner">
    <h3 class="banner-heading">Your learning Management System</h3>
    <h5 class="banner-heading">Signed in as: <%= current_user.name %> | <%= current_user.authorization.titlecase %> account</h5>
    <nav class=<%= privileged ? "nav-6" : "nav-5" %>>
        <%= button_to "Home", root_path, method: :get %>
        <%= button_to "Explore Courses", courses_path, method: :get %>
        <%= button_to "Explore Lessons", categories_path, method: :get %>
        <%= button_to "Your Courses", {controller: :courses, action: :index, user_id: current_user.id}, method: :get %>
        <% if privileged %>
        <%= button_to "Create a Course", new_course_path, method: :get %>
        <% end %>
        <%= button_to "Logout", {controller: :users, action: 'destroy', id: current_user.id}, method: :delete %>
    </nav>
</div>


<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LMS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render partial: 'layouts/banner' %>
    <% end %>
    <%= yield %>
  </body>
</html>